{
  "sksl": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 resolution;\nuniform shader image;\nuniform half2 image_size;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nmat3 FLT_flutter_local_yRotation(float angle)\n{\n    mat3 rotOut = mat3(vec3(1.0, 0.0, 0.0), vec3(0.0, 1.0, 0.0), vec3(0.0, 0.0, 1.0));\n    rotOut[0] = vec3(cos(angle), 0.0, sin(angle));\n    rotOut[2] = vec3(-sin(angle), 0.0, cos(angle));\n    return rotOut;\n}\n\nmat3 FLT_flutter_local_zRotation(float angle)\n{\n    mat3 rotOut = mat3(vec3(1.0, 0.0, 0.0), vec3(0.0, 1.0, 0.0), vec3(0.0, 0.0, 1.0));\n    rotOut[0] = vec3(cos(angle), -sin(angle), 0.0);\n    rotOut[1] = vec3(sin(angle), cos(angle), 0.0);\n    return rotOut;\n}\n\nvoid FLT_main()\n{\n    vec2 fragCoord = FLT_flutter_local_FlutterFragCoord();\n    vec4 iMouse = vec4(50.0, 200.0, 0.0, 0.0);\n    vec2 uv = fragCoord / resolution;\n    float yaw = ((uv.x * 2.0) - 1.0) * 3.1415927410125732421875;\n    float pitch = (((uv.y * 2.0) - 1.0) * 3.1415927410125732421875) / 2.0;\n    float len = cos(pitch);\n    vec3 point;\n    point.x = cos(yaw) * len;\n    point.y = sin(yaw) * len;\n    point.z = sin(pitch);\n    float param = ((((1.0 - (iMouse.y / resolution.y)) * 2.0) - 1.0) * 3.1415927410125732421875) / 2.0;\n    float param_1 = (((iMouse.x / resolution.x) * 2.0) - 1.0) * 3.1415927410125732421875;\n    point = (FLT_flutter_local_yRotation(param) * FLT_flutter_local_zRotation(param_1)) * point;\n    pitch = asin(point.z);\n    len = cos(pitch);\n    yaw = atan(point.y, point.x);\n    uv.x = ((yaw / 3.1415927410125732421875) + 1.0) / 2.0;\n    uv.y = (((pitch * 2.0) / 3.1415927410125732421875) + 1.0) / 2.0;\n    fragColor = image.eval(image_size *  uv);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
  "stage": 1,
  "target_platform": 2,
  "uniforms": [
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 0,
      "name": "resolution",
      "rows": 2,
      "type": 10
    },
    {
      "array_elements": 0,
      "bit_width": 0,
      "columns": 1,
      "location": 1,
      "name": "image",
      "rows": 1,
      "type": 12
    }
  ]
}